version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        volumes:
          - $PWD/elasticsearch/esdata:/usr/share/elasticsearch/data
        networks:
            - elastic
        ports:
            - 9200:9200
            - 9300:9300
        restart: always

    kibana:
        image: docker.elastic.co/kibana/kibana:7.0.0
        container_name: kibana
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_URL: http://elasticsearch:9200/
        links:
            - elasticsearch
        ports:
            - 5601:5601
        networks:
            - elastic

    logstash:
        image: docker.elastic.co/logstash/logstash:7.0.0
        container_name: logstash
        environment:
            - node.name=logstash
        volumes:
            - "$PWD/logstash/pipeline:/usr/share/logstash/pipeline"
            - "$PWD/logstash/data:/tmp/data"
        ports:
            - 8801:8801
        links:
            - elasticsearch
        networks:
            - elastic
        restart: always

networks:
    elastic: